from .Azure import delete_selray_vms
from .Azure import delete_unattached_selray_disks
from .Azure import delete_unused_proxy_nsgs_for_cleanup
from .Azure import delete_unused_proxy_public_ips_for_cleanup
from .Azure import delete_unused_proxy_vnets_for_cleanup
from .Azure import list_selray_vms
from .Azure import create_selray_vm
from .Azure import rotate_ip_if_needed
from .Azure import delete_vm_by_name
