username_field = 'type="email"'
password_field = 'type="password"'
fail = "Incorrect user ID or password"
pre_login_code = """
try:
    # Wait up to 5 seconds for the button to be visible and enabled
    sign_in_button = page.locator("#idp_SignInButton")
    sign_in_button.wait_for(state="visible", timeout=5000)

    # Click it
    sign_in_button.click()
except PlaywrightTimeoutError:
    pass
"""