url = "https://portal.azure.com"
username_field = 'type="email"'
password_field = 'type="password"'
fail = "Your account or password is incorrect"
invalid_username = "We couldn't find an account with that username"