username_field = 'type="email"'
password_field = 'type="password"'
fail = "Invalid credentials"
url = "https://portal.azure.com"
pre_password_code = """
from patchright.sync_api import TimeoutError as PlaywrightTimeoutError
from time import sleep
try:
    email = page.get_by_label("Email Address")
    email.wait_for(state="visible", timeout=15_000)
    email.fill(f"{spray_config.username}")
    email.press("Enter")
    sleep(1)
except PlaywrightTimeoutError:
    print("Email field not visible in time; continuing.")
except Exception:
    traceback.print_exc()  # shows real error details
"""
